
four:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

# Position Controllers ---------------------------------------
joint1_position_controller:
type: position_controllers/JointPositionController
joint: chassis_to_wheel1
pid: {p: 100.0, i: 0.01, d: 10.0}


# Position Controllers ---------------------------------------
joint2_position_controller:
type: position_controllers/JointPositionController
joint: chassis_to_wheel2
pid: {p: 100.0, i: 0.01, d: 10.0}


# Position Controllers ---------------------------------------
joint3_position_controller:
type: position_controllers/JointPositionController
joint: chassis_to_wheel3
pid: {p: 100.0, i: 0.01, d: 10.0}


# Position Controllers ---------------------------------------
joint4_position_controller:
type: position_controllers/JointPositionController
joint: chassis_to_wheel4
pid: {p: 100.0, i: 0.01, d: 10.0}
